dist: focal
cache: packages

matrix:
  include:
    - language: r
      r: oldrel
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=/usr/bin/python3
      # install the python package first
      before_install:
        - sudo apt-get update && sudo apt-get install -y python3 python3-setuptools python3-dev python3-pip
        - sudo python3 -m pip install --upgrade pip
        - sudo python3 -m pip install numpy pandas
        - python3 setup.py install --user

    - language: r
      r: release
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=/usr/bin/python3
      # install the python package first
      before_install:
        - sudo apt-get update && sudo apt-get install -y python3 python3-setuptools python3-dev python3-pip
        - sudo python3 -m pip install --upgrade pip
        - sudo python3 -m pip install numpy pandas
        - python3 setup.py install --user

    - language: r
      r: devel
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=/usr/bin/python3
      # install the python package first
      before_install:
        - sudo apt-get update && sudo apt-get install -y python3 python3-setuptools python3-dev python3-pip
        - sudo python3 -m pip install --upgrade pip
        - sudo python3 -m pip install numpy pandas
        - python3 setup.py install --user

    - language: python
      python: 3.7
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.8
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.9
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

  # allow_failures:
  #   - r: oldrel
  #   - r: release
  #   - r: devel

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
